name: Bug Report
description: Report a bug or crash in the software
title: "[Bug Report]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report. Please include as much information as possible so the issue can be replicated and identified.
  - type: dropdown
    id: hos-version
    attributes:
      label: Switch Firmware Version
      description: Which Nintendo Switch firmware (HOS) version are you running?
      options:
        - 18.1.0 (Latest)
        - 18.0.1
        - 18.0.0
        - 17.0.1
        - 17.0.0
        - 16.1.0
        - 16.0.3
        - 16.0.2
        - 16.0.1
        - 16.0.0
        - Other (please specify in issue description)
    validations:
      required: true
  - type: dropdown
    id: ams-version
    attributes:
      label: Atmosphère Version
      description: Which version of Atmosphère are you using?
      options:
        - 1.7.1 (Latest)
        - 1.7.0
        - 1.6.2
        - 1.6.1
        - 1.6.0
        - 1.5.5
        - 1.5.4
        - 1.5.3
        - 1.5.2
        - 1.5.1
        - 1.5.0
        - Other (please specify in issue description)
    validations:
      required: true
  - type: dropdown
    id: mc-version
    attributes:
      label: Mission Control Version
      description: Which version of Mission Control are you using?
      options:
        - 0.11.1 (Latest)
        - 0.11.0
        - 0.10.0
        - 0.9.4
        - 0.9.3
        - 0.9.2
        - 0.9.1
        - 0.9.0
        - Other (please specify in issue description)
    validations:
      required: true
  - type: dropdown
    id: boot-method
    attributes:
      label: Boot Method
      description: Which bootloader are you using to launch Atmosphère?
      options:
        - Fusée
        - Hekate
        - Unsure
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe the issue you are experiencing. Where does the issue occur? How can it be reproduced?
      placeholder: Please describe your issue here.
    validations:
      required: true
  - type: textarea
    id: error-report
    attributes:
      label: Error Report
      description: If your issue involves the console crashing with an error screen, please attach the error report here.
      placeholder: Please attach error report here.
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Sometimes issues do not occur universally and may be caused by a factor unique to your setup. Add any additional contextual information about your environment here, eg. which other custom sysmodules are you running, are you booting sysnand or emummc, did you install Atmosphère or Mission Control as part of some unofficial third-party release/distribution etc
      placeholder: Please provide any additional context here.
